apiVersion: apps/v1 
kind: Deployment
metadata:
  name: vmapp
  labels: 
    app: vmapp
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: vmapp
  template:
    metadata:
      labels:
        app: vmapp
    spec:
      containers:
      - name: vmapp
        image: us-east1-docker.pkg.dev/quick-bonfire-416805/jenkins-gcp-rep/appweb:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: vm-service
  labels:
    app: vmapp 
spec:
  selector:
    app: vmapp 
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
